theme: jekyll-theme-cayman
title: Análise temporal
description: Utilizando ambiente do RStudio e método de prais winsten para calcular tendência temporal (2013-2019) do coeficiente de mortalidade infantil em São Paulo 
